"""YAML config write-back — serialize Pydantic models back to YAML files.

The config files are the source of truth. This module writes updated config
back to the YAML files, preserving the structure expected by the config loader.

Comment preservation is NOT supported — YAML comments are lost on write-back.
The files are regenerated from the Pydantic models with a header comment.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from seeker_os.config import CONFIG_DIR, FiltersConfig, ProfileConfig, invalidate_settings_cache


def _clean_none(value: Any) -> Any:
    """Remove None values and empty dicts/lists for cleaner YAML output."""
    if isinstance(value, dict):
        return {k: _clean_none(v) for k, v in value.items() if v is not None}
    if isinstance(value, list):
        cleaned = [_clean_none(v) for v in value if v is not None]
        return cleaned
    return value


def write_profile(profile: ProfileConfig, path: Path | None = None) -> Path:
    """Write ProfileConfig to profile.yml.

    Returns the path written to.
    """
    if path is None:
        path = CONFIG_DIR / "profile.yml"

    data = profile.model_dump()
    data = _clean_none(data)

    header = (
        "# Seeker OS — User Profile\n"
        "# This file is .gitignore'd. Do not commit personal data.\n"
        "# Generated by Seeker OS settings UI.\n\n"
    )

    yaml_text = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    path.write_text(header + yaml_text, encoding="utf-8")
    invalidate_settings_cache()
    return path


def write_filters(filters_config: FiltersConfig, path: Path | None = None) -> Path:
    """Write FiltersConfig to filters.yml.

    Returns the path written to.
    """
    if path is None:
        path = CONFIG_DIR / "filters.yml"

    data = filters_config.model_dump()
    data = _clean_none(data)

    header = (
        "# Seeker OS — Filter Configuration\n"
        "# This file contains NO personal data and can be committed to the repo.\n"
        "# Personal values (comp floor, blacklist, location) are in profile.yml.\n"
        "# Generated by Seeker OS settings UI.\n\n"
    )

    yaml_text = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    path.write_text(header + yaml_text, encoding="utf-8")
    invalidate_settings_cache()
    return path


def write_accuracy_rules(rules: list[dict], path: Path | None = None) -> Path:
    """Write accuracy rules to accuracy_rules.yml.

    Args:
        rules: List of rule dicts (id, description, type, severity, phrases/technologies/patterns)
        path: Optional path override

    Returns the path written to.
    """
    if path is None:
        path = CONFIG_DIR / "accuracy_rules.yml"

    data = {"rules": rules}
    data = _clean_none(data)

    header = (
        "# Seeker OS — Resume Accuracy Rules\n"
        "# Validated programmatically after every resume generation.\n"
        "# High severity violations block; medium severity warns.\n"
        "# Generated by Seeker OS settings UI.\n\n"
    )

    yaml_text = yaml.dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
    path.write_text(header + yaml_text, encoding="utf-8")
    invalidate_settings_cache()
    return path
